# Generated by Django 4.0.2 on 2022-08-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_register_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registation',
        ),
    ]
